"""add push subscription model

Revision ID: 004dbb570159
Revises: a8335aebba20
Create Date: 2025-08-11 16:47:13.104889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004dbb570159'
down_revision = 'a8335aebba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
