"""add podcast and user roles

Revision ID: 097928f42acb
Revises: a8335aebba20
Create Date: 2026-02-14 08:13:02.719825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097928f42acb'
down_revision = 'a8335aebba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('exercises_completed', sa.Integer(), nullable=True),
    sa.Column('workout_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_progress_date'), ['date'], unique=False)

    op.create_table('game_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_score_timestamp'), ['timestamp'], unique=False)

    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcast_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_timestamp'))

    op.drop_table('podcast')
    with op.batch_alter_table('game_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_score_timestamp'))

    op.drop_table('game_score')
    with op.batch_alter_table('fitness_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_progress_date'))

    op.drop_table('fitness_progress')
    # ### end Alembic commands ###
