"""last message read time

Revision ID: 194cdcea178a
Revises: d2be7663fb88
Create Date: 2025-07-23 19:38:27.328630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194cdcea178a'
down_revision = 'd2be7663fb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    # ### end Alembic commands ###
