"""post category and tags

Revision ID: 50ceedbb83ae
Revises: bcfa88c9efb2
Create Date: 2025-07-23 19:26:24.664395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ceedbb83ae'
down_revision = 'bcfa88c9efb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
