"""add podcast model

Revision ID: 7d9043112ee3
Revises: f666ce65e096
Create Date: 2026-02-14 08:04:58.925112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9043112ee3'
down_revision = 'f666ce65e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcast_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_timestamp'))

    op.drop_table('podcast')
    # ### end Alembic commands ###
