"""Q&A sessions

Revision ID: d1a2ebef023d
Revises: 6a408325346c
Create Date: 2025-07-23 19:42:17.115039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a2ebef023d'
down_revision = '6a408325346c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_session_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_session_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_qa_session_end_time'))

    op.drop_table('qa_session')
    # ### end Alembic commands ###
